import React, { useEffect, useRef, useState } from "react";
import { getToken, getUserDetails } from "../../../utils/auth";
import axios from "axios";
import { bdBackupApi, dbListApi, executeQueryApi, tableListApi } from "../../../api/endpoints";
import DataTableFullData from "../../../components/common/DataTableFullData";
import { Spinner } from "@nextui-org/react";
import { useNavigate } from "react-router-dom";
import { toastMsg } from "../../../utils/utils";

export default function QueryEditorUI() {
  const [selectedDb, setSelectedDb] = useState("");
  const [query, setQuery] = useState("");
  const textareaRef = useRef(null);
  const [dbList, setDbList] = useState([]);
  const [tablesList, setTableList] = useState([]);
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  const [isButtonDisabled, setIsButtonDisabled] = useState(false);
  const [isDbLoading, setIsDbLoading] = useState(false);
  const [isTableLoading, setIsTableLoading] = useState(false);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [hint, setHint] = useState(false);
  
  // New State for collapsing/expanding sidebar
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [isDownloading, setIsDownloading] = useState(false);

  const profile = getUserDetails();
  const token = getToken();
  const navigator = useNavigate();

  useEffect(() => {
    const fetchDb = async () => {
      if (!profile?.roleDtls?.some((item) => item?.id == 1)) {
        toastMsg("Permission Denied!!!", "blank");
        setTimeout(() => {
          navigator(-1);
        }, 5000);
        return;
      }
      setIsDbLoading(true);
      try {
        const response = await axios.post(
          dbListApi,
          {},
          { headers: { Authorization: `Bearer ${token}` } }
        );
        if (response?.data?.status) {
          setDbList(response?.data?.data);
        }
      } catch {
        console.log("error", error);
      } finally {
        setIsDbLoading(false);
      }
    };
    fetchDb();
  }, [token]);

  useEffect(() => {
    const fetchTable = async () => {
      setIsTableLoading(true);
      setTableList([]);
      try {
        const response = await axios.post(
          tableListApi,
          { conn: selectedDb },
          { headers: { Authorization: `Bearer ${token}` } }
        );
        if (response?.data?.status) {
          setTableList(response?.data?.data);
        }
      } catch {
        console.log("error", error);
      } finally {
        setIsTableLoading(false);
      }
    };
    if (token) {
      fetchTable();
    }
  }, [token, selectedDb]);

  const executeSql = async () => {
    setIsButtonDisabled(true);
    let statement = query;
    if (textareaRef.current) {
      const { selectionStart, selectionEnd } = textareaRef.current;
      if (selectionStart !== selectionEnd) {
        statement = query.substring(selectionStart, selectionEnd);
      }
    }
    try {
      const response = await axios.post(
        executeQueryApi,
        { conn: selectedDb, statement: statement },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      if (response?.data?.status) {
        setData(response?.data?.data);
        setError("");
      } else {
        setData(null);
        setError(response?.data?.message);
      }
    } catch (error) {
      console.log("error", error);
      setData(null);
      setError("Something went wrong");
    } finally {
      setIsButtonDisabled(false);
    }
  };

  const handleTableClick = (tableName) => {
    const trimmed = query.trim();

    if (!trimmed) {
      setQuery(`SELECT * FROM ${tableName} LIMIT 1`);
      setIsAutoGenerated(true);
      return;
    }

    if (isAutoGenerated) {
      const regex = /(FROM\s+)([a-zA-Z0-9_."]+)(\s+LIMIT\s+1)/i;
      if (regex.test(query)) {
        const updated = query.replace(regex, `$1${tableName}$3`);
        setQuery(updated);
        setIsAutoGenerated(true);
        return;
      }

      setQuery(`SELECT * FROM ${tableName} LIMIT 1`);
      setIsAutoGenerated(true);
      return;
    }

    setHint(true);
    setTimeout(() => setHint(false), 800);
  };
  
  const handleDownloadBackup = async () => {
    setIsDownloading(true);
    try {
      const response = await axios.post(
        bdBackupApi,
        { conn: selectedDb },
        { headers: { Authorization: `Bearer ${token}` } } // Standard JSON processing
      );

      if (response.data.status) {
        const { file_name, file_blob } = response.data.data;

        // 1. Convert the base64 string payload back into raw binary bytes
        const byteCharacters = atob(file_blob);
        const byteNumbers = new Array(byteCharacters.length);
        for (let i = 0; i < byteCharacters.length; i++) {
          byteNumbers[i] = byteCharacters.charCodeAt(i);
        }
        const byteArray = new Uint8Array(byteNumbers);
        
        // 2. Wrap the byte arrays inside a native browser download Blob container
        const blob = new Blob([byteArray], { type: "application/zip" });
        const downloadUrl = window.URL.createObjectURL(blob);
        
        // 3. Create a temporary anchor element link to trigger file save dialog automatically
        const link = document.createElement("a");
        link.href = downloadUrl;
        link.setAttribute("download", file_name);
        document.body.appendChild(link);
        link.click();
        
        // Clean up browser resources
        link.remove();
        window.URL.revokeObjectURL(downloadUrl);
        
        toastMsg(response.data.message, "success");
      } else {
        console.error("Backup processing layout exception:", response.data.message);
        toastMsg("Backup compilation issue encountered.", "error","top-center");
      }

    } catch (error) {
      console.error("Backup processing layout exception:", error);
      toastMsg("Failed to process database backup file payload.", "error");
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div
      className={`${
        isDbLoading ? "pointer-events-none filter blur-sm" : ""
      } p-1 bg-gray-100 min-h-screen`}
    >
      <div className="bg-white shadow rounded p-1">
        {/* Toggle Button Container to overlay nicely */}
        <div className="mb-2 flex items-center justify-between px-2">
          <button
            onClick={() => setIsSidebarOpen(!isSidebarOpen)}
            className="bg-gray-200 hover:bg-gray-300 text-gray-700 px-3 py-1 text-xs font-medium rounded flex items-center gap-1 transition-colors duration-200"
          >
            {isSidebarOpen ? "← Hide Sidebar" : "→ Show Sidebar"}
          </button>
          <button
            onClick={handleDownloadBackup}
            disabled={isDownloading}
            className={`px-4 py-2 text-white rounded ${
              isDownloading ? "bg-gray-400 cursor-not-allowed" : "bg-green-600 hover:bg-green-700"
            }`}
          >
            {isDownloading ? "Generating Backup..." : `Download Backup for (${selectedDb})`}
          </button>
        </div>

        {/* 3 Column Layout dynamically controlled */}
        <div className="grid grid-cols-12 gap-4">
          {/* LEFT SIDEBAR */}
          <div
            className={`${
              isSidebarOpen ? "col-span-3 block" : "hidden"
            } bg-gray-50 border rounded p-3 transition-all duration-300`}
          >
            <h3 className="font-semibold text-sm mb-2">Database</h3>

            <select
              className="w-full border p-2 rounded"
              value={selectedDb}
              onChange={(e) => setSelectedDb(e.target.value)}
            >
              {dbList.map((db, i) => (
                <option key={i} value={db?.value}>
                  {db?.label}
                </option>
              ))}
            </select>

            <h3 className="font-semibold text-sm mt-4 mb-2">Tables</h3>

            <div className="h-[400px] overflow-y-scroll border p-2 rounded bg-white">
              {tablesList.map((t, i) => (
                <div
                  key={i}
                  className={`${
                    t?.relkind == "f"
                      ? "text-red-500"
                      : t?.relkind == "v"
                      ? "text-yellow-600"
                      : t?.relkind == "m"
                      ? "text-yellow-900"
                      : "text-blue-700"
                  } cursor-pointer hover:underline text-sm py-1`}
                  onClick={() => handleTableClick(t?.name)}
                  title={t?.table_type}
                >
                  {t?.name}
                </div>
              ))}
              {isTableLoading && <Spinner />}
            </div>
          </div>

          {/* EDITOR (Changes from col-span-9 to col-span-12 automatically) */}
          <div
            className={`${
              isSidebarOpen ? "col-span-9" : "col-span-12"
            } transition-all duration-300`}
          >
            <textarea
              ref={textareaRef}
              rows={5}
              className={`w-full border rounded p-3 font-mono transition-all duration-300 text-xs
                        ${
                          hint
                            ? "border-yellow-500 text-gray-500 bg-yellow-50 shadow-md"
                            : "border-gray-300"
                        }`}
              placeholder="Write your SQL query here..."
              value={query}
              onChange={(e) => {
                setQuery(e.target.value);
                setIsAutoGenerated(false);
              }}
            />

            <div className="mt-3 flex gap-3">
              <button
                disabled={isButtonDisabled}
                onClick={executeSql}
                className={`${
                  isButtonDisabled
                    ? "bg-gray-600 hover:bg-gray-300"
                    : "bg-blue-600 hover:bg-blue-700"
                } text-white px-4 py-2 rounded`}
              >
                Execute
              </button>
            </div>

            {/* Data Output */}
            <div
              className={`${
                isButtonDisabled ? "pointer-events-none filter blur-sm" : ""
              } mt-5 bg-gray-50 border p-3 rounded`}
            >
              {error && <p className="text-red-600 font-medium">{error}</p>}

              {data?.headers && data?.data ? (
                <DataTableFullData
                  title={"Data Output"}
                  startingItemsPerPage={10}
                  isExport={true}
                  headers={[
                    { label: "#", key: "serial" },
                    ...(data.headers?.map((header) => ({
                      label: header,
                      key: header,
                    }))),
                  ]}
                  data={data.data}
                  renderRow={(item, idx) => (
                    <tr key={idx}>
                      <td className="px-3 py-2 border">{idx + 1}</td>
                      {data.headers.map((header, key) => (
                        <td key={key} className="px-3 py-2 border">
                          {String(item?.[header])}
                        </td>
                      ))}
                    </tr>
                  )}
                />
              ) : data ? (
                <p className="text-green-500">{data}</p>
              ) : (
                !error && <p className="text-gray-500">No Data Found</p>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}